<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>UnityBrowser</AssemblyName>
    <RootNamespace>UnityBrowser</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Product>Unity Browser</Product>
    <Authors>TaylorMouse</Authors>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="app.ico" />
    <EmbeddedResource Include="Resources/fsb_vorbis_setups.bin" LogicalName="UnityBrowser.fsb_vorbis_setups.bin" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.1.0" />
    <PackageReference Include="LZMA-SDK" Version="22.1.1" />
    <PackageReference Include="NVorbis" Version="0.10.5" />
    <PackageReference Include="Kyaru.Texture2DDecoder" Version="0.17.1" />
    <PackageReference Include="Kyaru.Texture2DDecoder.Windows" Version="0.2.0" />
  </ItemGroup>
</Project>
